### ISSUE TITLE
docker support

### ISSUE THREAD

**Issue by ghost** [socioboard/Socioboard-5.0#102]
Did you have a docker-compose for deploy ?

**Comment by Sathish-Globussoft** [comment]
No, Currently we dont have.

**Comment by mihazs** [comment]
+1 for docker version

**Comment by nickwild-999** [comment]
+1 for docker version

**Comment by leonardoborlot** [comment]
have you any one stack or docker compose?

**Comment by mtcaddy** [comment]
any update on docker? Happy to help.

**Comment by TechnologyClassroom** [comment]
The first step to making a docker compose script would be to make a bash script to install.  No one has published one yet.

**Comment by rsmithlal** [comment]
I will take a look at what's required to get this running in docker and script the install process. This seems like an interesting and useful platform and if it can help us with our social media workload I would be happy to work with you to contribute this

**Comment by mtcaddy** [comment]
> I will take a look at what's required to get this running in docker and script the install process. This seems like an interesting and useful platform and if it can help us with our social media workload I would be happy to work with you to contribute this

I'm happy to set it up with you.

**Comment by rsmithlal** [comment]
@mtcaddy sorry, I commented after just discovering the software and not trying it out. I signed up to the free plan of the commercial version and it had so many bugs that it was unusable. Lots of CORS issues in the front end. I would like this software to be worth my time, but right now it isn't.

**Comment by TechnologyClassroom** [comment]
@rsmithlal Can you share your scripts?

**Comment by rsmithlal** [comment]
@TechnologyClassroom I didn't end up writing more than just the initial couple of empty files because realized that I hadn't tried the software yet and had no idea what it was like or if it was worth investing time in. The bugs that I encountered were with the commercial production software and not the open source edition, and they don't have a clear way of reporting issues with that software as far as I could see. No contact email listed or open bug tracker portal.

**Comment by TechnologyClassroom** [comment]
@rsmithlal I see.  I think this is also the bug tracker for that.

**Comment by stvhanna** [comment]
@rsmithlal Did you find an alternative since Socioboard appears to have bugs and not worth dockerizing right now?

**Comment by rsmithlal** [comment]
Unfortunately not! I didn't need the features bad enough to keep looking extensively. It's something that I will be building into my open source community engine, though. It's not released yet, but you can find it in my profile if you're interested in something like this and would like to keep up to date and/or help build it!  ---- On Tue, 24 Nov 2020 20:29:38 -0330  notifications@github.com  wrote ----
@rsmithlal Did you find an alternative since Socioboard appears to have bugs and not worth dockerizing right now?

**Comment by kenjibailly** [comment]
Would love to see docker support :)

**Comment by tiritibambix** [comment]
Oh yes please, we need this ;)

**Comment by ovizii** [comment]
sadly not going to happens since it has been "requested" for about 3 years already

**Comment by axe312ger** [comment]
How about you people create your own container setup and publish it?

Open Source is about collaboration :)

**Comment by ovizii** [comment]
> How about you people create your own container setup and publish it?
> 
> Open Source is about collaboration :)

Very true, but my guess is people who could create their own container setup wouldn't be asking for one here :-)

**Comment by tiritibambix** [comment]
> but my guess is people who could create their own container setup wouldn't be asking for one here

Very true. If I had the knowledge or the time to learn it, I wouldn't be asking here :p

**Comment by vaughngx4** [comment]
Uhh my bad, I have located developer docs. <3

**Comment by vaughngx4** [comment]
@TechnologyClassroom Thanks! I am separating to avoid running all services in a single container, I won't separate the api from the frontend to avoid any unexpected errors. So far I have 3 containers being `socioboard`, `socioboard-mysql` and `socioboard-mongo`. Using alpine as the base image for the main container. Question: Is it necessary to set social media api details in the configs or can that be done via the frontend?

**Comment by TechnologyClassroom** [comment]
I think that is all handled in the configs, but I have not actually seen the web interface yet other than screenshots others have posted.

**Comment by vaughngx4** [comment]
I faffed around with containerizing it on stream the other day if anyone is interested. Keep in mind I hadn't found all the docs and stuff at that point xD - https://www.twitch.tv/videos/1517387240

**Comment by jon4short** [comment]
> @TechnologyClassroom Thanks! I am separating to avoid running all services in a single container, I won't separate the api from the frontend to avoid any unexpected errors. So far I have 3 containers being `socioboard`, `socioboard-mysql` and `socioboard-mongo`. Using alpine as the base image for the main container. Question: Is it necessary to set social media api details and/or mail details in the configs or can that be done via the frontend?

The developers have mentioned in one of the setup videos that it has to be done in the configs in the backend. Not sure why as it does have a frontend for it.

**Comment by vaughngx4** [comment]
@jon4short I see, thank you. In the video above I was using `sed` but I've switched to editing with `jq` since the placeholders in the config files are not uniform. I've added Docker env vars for each entry in the config that needs to be changed. All `local.socioboard.com` and `localhost` entries will be replaced with the domain specified in Docker env. So there will be options to set all configs from the backend(copy pasted for like an hour but it works. Will open a PR when it's done.

**Comment by vaughngx4** [comment]
> @vaughngx4 The closest thing to GNU/Linux documentation is the work that was posted to [issue 112](https://github.com/socioboard/Socioboard-5.0/issues/112). What I wrote [earlier in this thread](https://github.com/socioboard/Socioboard-5.0/issues/102#issuecomment-669660574) still applies. Once we have a functional bash script to install and configure a working site with sane defaults, a docker file would be trivial to make. On the other hand if someone were to make a docker compose file out of the findings from that issue, making a bash script from the docker file would also be trivial.

@TechnologyClassroom Are these 3 lines of config still necessary? 
```
"base_path": "../../media",
"payment_path": "../../media/payments",
"template": "public/template/paymentTemplate.html"
```

**Comment by vaughngx4** [comment]
I get the following during composer install:
```
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

Problem 1
- league/flysystem is locked to version 1.1.9 and an update of this package was not requested.
- league/flysystem 1.1.9 requires ext-fileinfo * -> it is missing from your system. Install or enable PHP's fileinfo extension.
Problem 2
- league/mime-type-detection is locked to version 1.9.0 and an update of this package was not requested.
- league/mime-type-detection 1.9.0 requires ext-fileinfo * -> it is missing from your system. Install or enable PHP's fileinfo extension.
Problem 3
- nikic/php-parser is locked to version v4.13.2 and an update of this package was not requested.
- nikic/php-parser v4.13.2 requires ext-tokenizer * -> it is missing from your system. Install or enable PHP's tokenizer extension.
Problem 4
- psy/psysh is locked to version v0.10.8 and an update of this package was not requested.
- psy/psysh v0.10.8 requires ext-tokenizer * -> it is missing from your system. Install or enable PHP's tokenizer extension.
Problem 5
- tijsverkoyen/css-to-inline-styles is locked to version 2.2.4 and an update of this package was not requested.
- tijsverkoyen/css-to-inline-styles 2.2.4 requires ext-dom * -> it is missing from your system. Install or enable PHP's dom extension.
Problem 6
- phar-io/manifest is locked to version 2.0.1 and an update of this package was not requested.
- phar-io/manifest 2.0.1 requires ext-dom * -> it is missing from your system. Install or enable PHP's dom extension.
Problem 7
- phpunit/php-code-coverage is locked to version 9.2.6 and an update of this package was not requested.
- phpunit/php-code-coverage 9.2.6 requires ext-dom * -> it is missing from your system. Install or enable PHP's dom extension.
Problem 8
- phpunit/phpunit is locked to version 9.5.4 and an update of this package was not requested.
- phpunit/phpunit 9.5.4 requires ext-dom * -> it is missing from your system. Install or enable PHP's dom extension.
Problem 9
- theseer/tokenizer is locked to version 1.2.0 and an update of this package was not requested.
- theseer/tokenizer 1.2.0 requires ext-dom * -> it is missing from your system. Install or enable PHP's dom extension.
Problem 10
- league/flysystem 1.1.9 requires ext-fileinfo * -> it is missing from your system. Install or enable PHP's fileinfo extension.
- laravel/framework v8.83.5 requires league/flysystem ^1.1 -> satisfiable by league/flysystem[1.1.9].
- laravel/framework is locked to version v8.83.5 and an update of this package was not requested.

To enable extensions, verify that they are enabled in your .ini files:
- /etc/php8/php.ini
- /etc/php8/conf.d/00_curl.ini
- /etc/php8/conf.d/00_iconv.ini
- /etc/php8/conf.d/00_mbstring.ini
- /etc/php8/conf.d/00_opcache.ini
- /etc/php8/conf.d/00_openssl.ini
- /etc/php8/conf.d/00_xml.ini
- /etc/php8/conf.d/00_zip.ini
- /etc/php8/conf.d/01_mysqlnd.ini
- /etc/php8/conf.d/01_phar.ini
- /etc/php8/conf.d/02_mysqli.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-fileinfo --ignore-platform-req=ext-fileinfo --ignore-platform-req=ext-tokenizer --ignore-platform-req=ext-tokenizer --ignore-platform-req=ext-dom --ignore-platform-req=ext-dom --ignore-platform-req=ext-dom --ignore-platform-req=ext-dom --ignore-platform-req=ext-dom --ignore-platform-req=ext-fileinfo` to temporarily ignore these required extensions.
```

Am I missing php modules or configs or what?
Here are my dependancies:
```
RUN apk add --no-cache --upgrade \
    bash \
    jq \
    apache2 \
    apache2-utils \
    php8 \
    php8-apache2 \
    php8-mysqli \
    php8-opcache \
    php8-common \
    php8-cli \
    php8-curl \
    php8-xml \
    composer
```

**Comment by TechnologyClassroom** [comment]
> @TechnologyClassroom Are these 3 lines of config still necessary?

¯\\_(ツ)_/¯

**Comment by vaughngx4** [comment]
So, it's almost ready. However the frontend listens on `127.0.0.1:8000` by default and is therefore not accessable outside the container. I'm not familiar with Laravel or the LAMP stack, I will look into it later but if anyone knows how to change the bind address just drop a comment, thanks.

**Comment by vaughngx4** [comment]
> So, it's almost ready. However the frontend listens on `127.0.0.1:8000` by default and is therefore not accessable outside the container. I'm not familiar with Laravel or the LAMP stack, I will look into it later but if anyone knows how to change the bind address just drop a comment, thanks.

Fixed by running frontend using `php8 artisan serve --host=0.0.0.0 --port=8000`

**Comment by vaughngx4** [comment]
YO! It's done, seems to be working fine. However I don't know how to create a user(tried signing up and activating the account manually in the database using `update user_activations set activation_status = 1;` but I get 'undefined' error on signup and nothing in the database). If anyone knows how to or can get it working, please add to the docs in `Docker.README.md` (and let me know xD). Will open a PR now.

**Comment by vaughngx4** [comment]
![Screenshot_8](https://user-images.githubusercontent.com/72740493/177047304-fa3362bd-a0b9-41cb-94dc-73e3a63c02f8.png)

**Comment by vaughngx4** [comment]
Hi all! Apologies for the spam. It seems the developers are not very active. If anyone would like to discuss the project or other dev please join me on Discord: https://discord.gg/TSnvnjE6zP I will be available soon.

**Comment by ovizii** [comment]
@vaughngx4 no need to apologize, you've done what we all asked for. As soon as I have a moment, I'll give your fork a try.

**Comment by vaughngx4** [comment]
I've figured out administration. Will add to the Docker docs soon and update the other docs after.

**Comment by axe312ger** [comment]
Ohh wow, something happening here! Amazing folks, especially @vaughngx4 :)

**Comment by vaughngx4** [comment]
I think this issue can be close after the latest merge? Unless we want to wait until I get it running as non-root, with it's current vulnerabilities I don't like it running as root.

**Comment by tiritibambix** [comment]
> Docker container is ready to use. Admin UI and all.

That was fast ! Thank you so much !!

I still have to understand how to make it work though 😂

**Comment by TechnologyClassroom** [comment]
@tiritibambix https://github.com/socioboard/Socioboard-5.0/blob/master/Docker.README.md

**Comment by tiritibambix** [comment]
> https://github.com/socioboard/Socioboard-5.0/blob/master/Docker.README.md

Great ressource. Thank you. But there's more. Like, I need to understand how it literally works x)
Like where do I get `FACEBOOK_API_APP_ID`, `FACEBOOK_API_APP_SECRET`, `TWITTER_API_KEY`, `TWITTER_API_SECRET`, `TWITTER_API_APP_NAME`, etc...

And if ports 8000, 3000, 3001... are already in use, if I can change that.

I really got to study here :p

**Comment by vaughngx4** [comment]
> @tiritibambix The API details you will have to get from facebook, twitter etc. (Google facebook api keys and go from there). I haven't actually connected any APIs myself yet. As far as ports go, you can change which ports are exposed in `docker/docker-compose.yaml`. For example: to change the port the frontend is served on to port 8989 we would change `"8000:8000"` to `"8989:8000"`. You would also need to change the url scheme in `docker/socioboard/init.sh` to match (change port 8000 to 8989).

Regarding the API details, this gives the application functionality. The API details are used by the applications to perform functions like logging in, posting etc. These should not be linked to your personal accounts(you log in with those on the frontend).

**Comment by TechnologyClassroom** [comment]
This project should not duplicate the effort of rewriting documentation to get the API keys, but linking to the appropriate documentation for the various sites would be helpful to jump start people in the right direction.

**Comment by vaughngx4** [comment]
@TechnologyClassroom I agree. I've been focused on the Docker version thus far but will write more documentation as I make progress with the application.

**Comment by TechnologyClassroom** [comment]
At this rate, @vaughngx4 will squash all of the issue by next week.  lol

**Comment by vaughngx4** [comment]
> At this rate, @vaughngx4 will squash all of the issue by next week. lol

Haha! Issues? What issues? :P

**Comment by vaughngx4** [comment]
@tiritibambix You're welcome :)

**Comment by kenjibailly** [comment]
@vaughngx4 Thanks for making this happen.

I installed Socioboard and got access to the web interface.
Although I seem to stumble upon a few problems.
1. How do I login (which credentials) / Create an account? (doesn't seem to be working)
2. Portforwarding using nginx isn't working as expected:
```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name socioboard.mydomain.com;
    include /config/nginx/ssl.conf;
    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_app socioboard;
        set $upstream_port 8000;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
```

3. Would be nice for a documentation about the .env as well, but I see you're already working on that, thanks for that!

**Comment by vaughngx4** [comment]
@kenjibailly I'm actually just fixing it as I try it out. There seems to be an issue with oroxying currently, I'll check it out soon.

See Docker.README.md about creating an account(my fork, waiting for PR to merge).

**Comment by vaughngx4** [comment]
@kenjibailly See my latest PR. You can modify the nginx config if you'd like or simply put another nginx in front of the stack.

**Comment by kenjibailly** [comment]
> @kenjibailly I'm actually just fixing it as I try it out. There seems to be an issue with proxying currently, I'll check it out soon.
> 
> See Docker.README.md about creating an account ~(my fork, waiting for PR to merge).~ PR has been merged.

I started with a clean install using the git clone today.
I added the Twilio info to the .env, sendgrid info added to env, changed domain name in env. I didn't change the rest. 
Unfortunately I can't seem to make an account.
I don't get the desired notification, but rather get this one and takes forever to show up:
![image](https://user-images.githubusercontent.com/9883910/178770858-0a225a36-b405-426a-aa7a-dd338e25718c.png)

Note: I made 1 small modification to the docker-compose as it gives me an error when executing being this one:
```
ERROR: Network scb-net declared as external but specifies additional attributes (driver, ipam).
```
To get rid of this I just commented the last 5 lines out like this:
```
    # driver: bridge
    # ipam:
    #   config:
    #     - subnet: 172.16.32.0/16
    #       gateway: 172.16.32.1
```

The network seems to be created with the desired preferences when looking in portainer (not 100% sure)
![image](https://user-images.githubusercontent.com/9883910/178771566-d5697060-c745-4e91-bd2f-7cb0fbd529fa.png)
![image](https://user-images.githubusercontent.com/9883910/178771513-c8ee2dd7-152e-4e86-a320-10aa0ef65b25.png)

Let me know if I'm doing something wrong here.


Btw I'll have to try nginx later.

**Comment by kenjibailly** [comment]
> docker exec -it socioboard su-exec socioboard pm2 logs

So that means I can comment out the last 5 lines, correct?
It seems to connect with the desired containers, so I think that part is good.

So about the error logs, I couldn't find any that were triggered from the registration submit button.
I could however find these logs, but they are triggered when accessing the adminbro web page. 
```
5|admin.se | Wed, 13 Jul 2022 15:07:34 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at node_modules/admin-bro-expressjs/plugin.js:176:14
5|admin.se | Wed, 13 Jul 2022 15:08:11 GMT express-session deprecated undefined resave option; provide resave option at node_modules/admin-bro-expressjs/plugin.js:176:14
5|admin.se | Wed, 13 Jul 2022 15:08:11 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at node_modules/admin-bro-expressjs/plugin.js:176:14
5|admin.se | @rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
5|admin.se | @rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
5|admin.se | @rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
5|admin.se | @rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
5|admin.se | Wed, 13 Jul 2022 15:17:40 GMT express-session deprecated undefined resave option; provide resave option at node_modules/admin-bro-expressjs/plugin.js:176:14
5|admin.se | Wed, 13 Jul 2022 15:17:40 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at node_modules/admin-bro-expressjs/plugin.js:176:14
5|admin.se | @rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
5|admin.se | @rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
5|admin.se | @rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
5|admin.se | @rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
5|admin.se | Wed, 13 Jul 2022 16:49:59 GMT express-session deprecated undefined resave option; provide resave option at node_modules/admin-bro-expressjs/plugin.js:176:14
5|admin.se | Wed, 13 Jul 2022 16:49:59 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at node_modules/admin-bro-expressjs/plugin.js:176:14
```

I get a bunch of things info logs as well (green) that seem to say that everything is ready.

Thank you for helping out mate :)

**Comment by vaughngx4** [comment]
@kenjibailly Even though I added IPs they are not relevant, I'll look into changing how the network works but I'm not sure it will work without the last 5 lines. Try running the docker network create command from the build see script and uncommenting the 5 lines. The undefined error means the frontend can't reach the API. Are you using my fork with the latest updates? There were some domain issues I fixed, it could only run on localhost prior to the nginx update.

**Comment by vaughngx4** [comment]
`mixed content` errors fixed. Thanks @kenjibailly for finding the fix!

**Comment by CountOlaf87** [comment]
I'm trying to run this behind my Traefik reverse proxy with letsencrypt ssl certs, everything starts up fine, but I'm getting some mixed content errors when loading css. How can I fix this?

**Comment by vaughngx4** [comment]
@CountOlaf87 You have to force https. If the browser attempts to connect via http first, you will get mixed content errors. In nginx we managed to get it working using `add_header 'Content-Security-Policy' 'upgrade-insecure-requests';`

**Comment by CountOlaf87** [comment]
Did I mention I run it in docker? Could you guide me how to solve it?

**Comment by vaughngx4** [comment]
@CountOlaf87 I think this should work in Traefik:
```
labels:
  - "traefik.http.middlewares.testheader.headers.contentSecurityPolicy=upgrade-insecure-requests"
```

**Comment by CountOlaf87** [comment]
Thanks, but that doesn't seem to work, I'll have a look later to see if I can pass it on in the traefik config

**Comment by CountOlaf87** [comment]
Thanks @vaughngx4, Your comment did do the trick!

**Comment by lmoellendorf** [comment]
I read this thread, especially https://github.com/socioboard/Socioboard-5.0/issues/102#issuecomment-1184424973. So I tried with vaughngx4 fork repo. I added the URLs mentioned in https://github.com/vaughngx4/Socioboard-5.0/blob/development/docker/nginx/ssl/SSL.README.md with my base domain to my routers DNS server and confirmed that they all point to the docker host.

I try to sign up at https://socio.<my-base-domain>/register. If I submit I get "Registration failed!!". Then I checkhttps://socio.<ny-base-domain>/admin/resources/user_activations, but there are no records.

**Comment by vaughngx4** [comment]
> I read this thread, especially [#102 (comment)](https://github.com/socioboard/Socioboard-5.0/issues/102#issuecomment-1184424973). So I tried with vaughngx4 fork repo. I added the URLs mentioned in https://github.com/vaughngx4/Socioboard-5.0/blob/development/docker/nginx/ssl/SSL.README.md with my base domain to my router's DNS server and confirmed that they all point to the docker host.
> 
> I try to sign up at https://socio.my-base-domain/register. If I submit I get "Registration failed!!". Then I check https://socio.my-base-domain/admin/resources/user_activations, but there are no records.

This is probably a result of missing API info (Twilio is required).

However, I've since abandoned the project to lack of response from the developers and nothing working. See #399 .

**Comment by lmoellendorf** [comment]
Thank you. I added Twilio account information, but maybe not the expected IDs and Key. However, as you are the second one here who says that Socioboard does not work, I should better save my time and look for another solution - maybe [yours](https://github.com/vaughngx4/OpenSMM/tree/development).

**Comment by vaughngx4** [comment]
@lmoellendorf OpenSMM is a work in progress. However you can use the version on the main branch to post to Twitter. :)

**Comment by ovizii** [comment]
>  Please go through the Latest features and implementations you can find all these queries.
> 

DO you mind sharing a link? The releases page shows the last release from 2019? https://github.com/socioboard/Socioboard-5.0/releases

**Comment by sureshbabu1995** [comment]
Hi @ovizii 

Yes, There's some Release note update mis match, as we got out-collab and added a Docker Support for our repo

https://github.com/socioboard/Socioboard-5.0/blob/master/docker-build.sh

Please check this link ( and check in the Repo Main page -  https://github.com/socioboard/Socioboard-5.0 ), you'll see the docker-related code.

And thank you for checking on us, we love to help you more,  If you want more updates, we can collaborate as well.
