### ISSUE TITLE
[ERR_MODULE_NOT_FOUND]: Cannot find module '/opt/socioboard-api/User/core/unauthorized/unauthorized.routes.js'

### ISSUE THREAD

**Issue by FlorentPoinsaut** [socioboard/Socioboard-5.0#262]
Hello!

User service from Socioboard-5.1.0 branch doesn't start with this error:
```
0|user.ser | Error [ERR_MODULE_NOT_FOUND]: Cannot find module '~/User/core/unauthorized/unauthorized.routes.js' imported from /opt/socioboard-api/User/resources/routes/public.routes.js
0|user.ser |     at finalizeResolution (internal/modules/esm/resolve.js:276:11)
0|user.ser |     at moduleResolve (internal/modules/esm/resolve.js:699:10)
0|user.ser |     at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
0|user.ser |     at Loader.resolve (internal/modules/esm/loader.js:86:40)
0|user.ser |     at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)
0|user.ser |     at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)
0|user.ser |     at link (internal/modules/esm/module_job.js:55:36) {
0|user.ser |   code: 'ERR_MODULE_NOT_FOUND'
0|user.ser | }
```

Code searches for `~/User/core/unauthorized/unauthorized.routes.js` instead of `~/User/core/unAuthorized/unAuthorized.routes.js`

A one-liner to fix this:
`  grep -r '/unauthorized' ~/User/core ~/User/resources | grep import | cut -d ':' -f 1 | xargs sed -i 's:/unauthorized:/unAuthorized:g'`

Regards,

**Comment by sureshbabu1995** [comment]
Hi @FlorentPoinsaut

Great To hear a fix in a bug list, Hope it will be useful for other users till we update the document.

Thank you to mention the fix.
