### ISSUE TITLE
Error: ENOENT: no such file or directory, mkdir 'resources/Log/ResponseLog'

### ISSUE THREAD

**Issue by FlorentPoinsaut** [socioboard/Socioboard-5.0#263]
Hello!

Feeds and Update services from Socioboard-5.1.0 branch don't start with this error:
```
1|feeds.se | Error: ENOENT: no such file or directory, mkdir 'resources/Log/ResponseLog'
1|feeds.se |     at Object.mkdirSync (fs.js:987:3)
1|feeds.se |     at file://~/Publish/resources/Log/logger.log.js:14:6
1|feeds.se |     at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
1|feeds.se |     at async Loader.import (internal/modules/esm/loader.js:166:24) {
1|feeds.se |   errno: -2,
1|feeds.se |   syscall: 'mkdir',
1|feeds.se |   code: 'ENOENT',
1|feeds.se |   path: 'resources/Log/ResponseLog'
1|feeds.se | }
```

A one-liner workaround:
ln -s ~/Feeds/resources/log ~/Feeds/resources/Log && ln -s ~/Update/resources/log ~/Update/resources/Log 

Regards,

**Comment by sureshbabu1995** [comment]
Hi @FlorentPoinsaut

Great To hear a fix in a bug list, Hope it will be useful for other users till we update the document.

Thank you to mention the fix.
