### ISSUE TITLE
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '~/Common/Demo/medium/medium-demo.routes.js' imported from ~/User/resources/routes/public.routes.js

### ISSUE THREAD

**Issue by FlorentPoinsaut** [socioboard/Socioboard-5.0#286]
Hello!

User service from Socioboard-5.3.1 branch don't start with this error:

```
api_1    | 0|user.ser | Error [ERR_MODULE_NOT_FOUND]: Cannot find module '~/Common/Demo/medium/medium-demo.routes.js' imported from ~/User/resources/routes/public.routes.js
api_1    | 0|user.ser |     at finalizeResolution (internal/modules/esm/resolve.js:276:11)
api_1    | 0|user.ser |     at moduleResolve (internal/modules/esm/resolve.js:699:10)
api_1    | 0|user.ser |     at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
api_1    | 0|user.ser |     at Loader.resolve (internal/modules/esm/loader.js:86:40)
api_1    | 0|user.ser |     at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)
api_1    | 0|user.ser |     at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)
api_1    | 0|user.ser |     at link (internal/modules/esm/module_job.js:55:36) {
api_1    | 0|user.ser |   code: 'ERR_MODULE_NOT_FOUND'
api_1    | 0|user.ser | }
```

This import doesn't exist:
https://github.com/socioboard/Socioboard-5.0/blob/fc03145b17531c23893ac0a2279c7224b2e3c3e6/socioboard-api/User/resources/routes/public.routes.js#L14-L15

WorkAround: comment these lines

Regards,

**Comment by sureshbabu1995** [comment]
Hi, @FlorentPoinsaut 

Let me updated the missing files.
