### ISSUE TITLE
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '~/Common/Shared/config.shared.js' imported from ~/Common/Constants/bitly.constants.js

### ISSUE THREAD

**Issue by FlorentPoinsaut** [socioboard/Socioboard-5.0#287]
Hello!

User service from Socioboard-5.3.1 branch don't start with this error:

```
api_1    | 0|user.ser | Error [ERR_MODULE_NOT_FOUND]: Cannot find module '~/Common/Shared/config.shared.js' imported from ~/Common/Constants/bitly.constants.js
api_1    | 0|user.ser |     at finalizeResolution (internal/modules/esm/resolve.js:276:11)
api_1    | 0|user.ser |     at moduleResolve (internal/modules/esm/resolve.js:699:10)
api_1    | 0|user.ser |     at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
api_1    | 0|user.ser |     at Loader.resolve (internal/modules/esm/loader.js:86:40)
api_1    | 0|user.ser |     at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)
api_1    | 0|user.ser |     at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)
api_1    | 0|user.ser |     at link (internal/modules/esm/module_job.js:55:36) {
api_1    | 0|user.ser |   code: 'ERR_MODULE_NOT_FOUND'
api_1    | 0|user.ser | }
```

The file `~/Common/Shared/config.shared.js` doesn't exist at all...

Regards,

**Comment by sureshbabu1995** [comment]
Hi, @FlorentPoinsaut  Let me update the missing file.
