### ISSUE TITLE
npm run swagger fails

### ISSUE THREAD

**Issue by githubber** [socioboard/Socioboard-5.0#385]
Hello! Cool app!
I've followed all the instructions, everything seems ok EXCEPT ```npm run swagger``` fails in teh four microservice directories. Here is the the terminal output, and the log (they seem to say teh same thing). Can anyone tell me what's wrong?? Thank you.

```
me@host:/var/www/socioboard/socioboard-api/User$ npm run swagger

> socioboard-users@1.0.0 swagger /var/www/socioboard/socioboard-api/User
> node ./resources/views/swagger.config.js

file:///var/www/socioboard/socioboard-api/User/resources/views/swagger.config.js:179
await swagger(outputFile, endpointsFiles, doc);
^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)
    at async link (internal/modules/esm/module_job.js:42:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! socioboard-users@1.0.0 swagger: `node ./resources/views/swagger.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the socioboard-users@1.0.0 swagger script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/me/.npm/_logs/2022-07-13T23_42_14_546Z-debug.log
```

---
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'swagger' ]
2 info using npm@6.14.16
3 info using node@v12.22.12
4 verbose run-script [ 'preswagger', 'swagger', 'postswagger' ]
5 info lifecycle socioboard-users@1.0.0~preswagger: socioboard-users@1.0.0
6 info lifecycle socioboard-users@1.0.0~swagger: socioboard-users@1.0.0
7 verbose lifecycle socioboard-users@1.0.0~swagger: unsafe-perm in lifecycle true
8 verbose lifecycle socioboard-users@1.0.0~swagger: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/socioboard/socioboard-api/User/node_modules/.bin:/usr/local/sbin:/usr/local/>9 verbose lifecycle socioboard-users@1.0.0~swagger: CWD: /var/www/socioboard/socioboard-api/User
10 silly lifecycle socioboard-users@1.0.0~swagger: Args: [ '-c', 'node ./resources/views/swagger.config.js' ]
11 silly lifecycle socioboard-users@1.0.0~swagger: Returned: code: 1  signal: null
12 info lifecycle socioboard-users@1.0.0~swagger: Failed to exec swagger script
13 verbose stack Error: socioboard-users@1.0.0 swagger: `node ./resources/views/swagger.config.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1022:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid socioboard-users@1.0.0
15 verbose cwd /var/www/socioboard/socioboard-api/User
16 verbose Linux 5.4.0-28-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "swagger"
18 verbose node v12.22.12
19 verbose npm  v6.14.16
20 error code ELIFECYCLE
21 error errno 1
22 error socioboard-users@1.0.0 swagger: `node ./resources/views/swagger.config.js`
22 error Exit status 1
23 error Failed at the socioboard-users@1.0.0 swagger script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by nico-i** [comment]
Hi @githubber, I ran into the same issue. The solution for me was that the node version I used did not support async functions. I installed the newest version of node using nvm with [this guide](https://tecadmin.net/how-to-install-nvm-on-ubuntu-22-04/) and now `npm run swagger` runs without a hitch.

**Comment by sureshbabu1995** [comment]
Hello @githubber 

It appears that you have received the information you requested. I suggest we close this inactive thread for the time being. If you have any further concerns, you can create a new ticket.
